/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.etec.GUI;

//import br.gov.sp.etec.DAO.AlunosDAO;
import br.gov.sp.etec.DAO.CadastroAlunoDAO;
import br.gov.sp.etec.GUI.HomeGUI;
import br.gov.sp.etec.GUI.MensalidadesGUI;
import br.gov.sp.etec.conectar.UtilDAO;
import br.gov.sp.etec.modelagem.CadastroAluno;
import com.sun.media.sound.InvalidDataException;
//import br.gov.sp.etec.modelagem.Alunos;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tami
 */
public class GereAlunosGUI extends javax.swing.JFrame {

    /**
     * Creates new form Modelo
     */
    public GereAlunosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jPanelAlunos = new javax.swing.JPanel();
        jLabelAlunos = new javax.swing.JLabel();
        jPanelEstoque = new javax.swing.JPanel();
        jLabelEstoque = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelChamada = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonChama = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jTextFieldId = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldDtNascimento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jFormattedTextFieldTelefoneA = new javax.swing.JFormattedTextField();
        jButtonDelete1 = new javax.swing.JButton();
        jTextFieldNome1 = new javax.swing.JTextField();
        jTextFieldRg1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setToolTipText("Fechar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/icons8_Conference_32px.png"))); // NOI18N
        jLabel5.setText("Gerenciamento de Alunos");

        jLabelMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMinimizar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setText("_");
        jLabelMinimizar.setToolTipText("Minimizar");
        jLabelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel5)
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMinimizar))
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(121, 1, 740, 101);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(130, 525));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Voltar_18px.png"))); // NOI18N
        jLabel2.setText("Voltar");
        jLabel2.setToolTipText("Voltar para tela Home");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setDoubleBuffered(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanelHome.setBackground(new java.awt.Color(102, 0, 0));
        jPanelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelHome.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseExited(evt);
            }
        });

        jLabelHome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Home_18px.png"))); // NOI18N
        jLabelHome.setText("Home");
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAlunos.setBackground(new java.awt.Color(102, 0, 0));
        jPanelAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAlunos.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseExited(evt);
            }
        });

        jLabelAlunos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlunos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Alunos_18px.png"))); // NOI18N
        jLabelAlunos.setText("Alunos");

        javax.swing.GroupLayout jPanelAlunosLayout = new javax.swing.GroupLayout(jPanelAlunos);
        jPanelAlunos.setLayout(jPanelAlunosLayout);
        jPanelAlunosLayout.setHorizontalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlunosLayout.setVerticalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelEstoque.setBackground(new java.awt.Color(102, 0, 0));
        jPanelEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelEstoque.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEstoqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEstoqueMouseExited(evt);
            }
        });

        jLabelEstoque.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Estoque_18px.png"))); // NOI18N
        jLabelEstoque.setText("Estoque");
        jLabelEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelEstoqueLayout = new javax.swing.GroupLayout(jPanelEstoque);
        jPanelEstoque.setLayout(jPanelEstoqueLayout);
        jPanelEstoqueLayout.setHorizontalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEstoque)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelEstoqueLayout.setVerticalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Cabeçalho.png"))); // NOI18N

        jPanelChamada.setBackground(new java.awt.Color(102, 0, 0));
        jPanelChamada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelChamada.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelChamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelChamadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelChamadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelChamadaMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Chamada_18px_1.png"))); // NOI18N
        jLabel7.setText("Chamada");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelChamadaLayout = new javax.swing.GroupLayout(jPanelChamada);
        jPanelChamada.setLayout(jPanelChamadaLayout);
        jPanelChamadaLayout.setHorizontalGroup(
            jPanelChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelChamadaLayout.setVerticalGroup(
            jPanelChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastro.setBackground(new java.awt.Color(102, 0, 0));
        jPanelCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCadastro.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCadastroMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Cadastro_18px_3.png"))); // NOI18N
        jLabel9.setText("Cadastro");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelChamada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1, 1, 120, 590);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kids", "Juvenil - Adulto" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(130, 110, 120, 20);

        jButtonChama.setBackground(new java.awt.Color(102, 0, 0));
        jButtonChama.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonChama.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChama.setText("Buscar");
        jButtonChama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChamaActionPerformed(evt);
            }
        });
        jButtonChama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonChamaKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonChama);
        jButtonChama.setBounds(140, 140, 90, 40);

        jTextFieldSearch.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldSearch);
        jTextFieldSearch.setBounds(660, 140, 180, 25);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nome:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(660, 110, 50, 17);

        jTableAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableAlunos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "RG", "Telefone", "Endereço", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAlunos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTableAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlunos);
        if (jTableAlunos.getColumnModel().getColumnCount() > 0) {
            jTableAlunos.getColumnModel().getColumn(0).setResizable(false);
            jTableAlunos.getColumnModel().getColumn(1).setResizable(false);
            jTableAlunos.getColumnModel().getColumn(2).setResizable(false);
            jTableAlunos.getColumnModel().getColumn(3).setResizable(false);
            jTableAlunos.getColumnModel().getColumn(4).setResizable(false);
            jTableAlunos.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 720, 150);

        jButtonDelete.setBackground(new java.awt.Color(102, 0, 0));
        jButtonDelete.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Apagar");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jButtonDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonDeleteKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonDelete);
        jButtonDelete.setBounds(720, 460, 110, 40);

        jButtonAtualizar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        jButtonAtualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAtualizarKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonAtualizar);
        jButtonAtualizar.setBounds(720, 380, 110, 40);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(660, 170, 180, 10);

        jTextFieldId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldId.setEnabled(false);
        jPanel1.add(jTextFieldId);
        jTextFieldId.setBounds(140, 380, 180, 25);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ID:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(140, 350, 50, 17);

        jTextFieldDtNascimento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDtNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDtNascimento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jTextFieldDtNascimento);
        jTextFieldDtNascimento.setBounds(440, 520, 180, 25);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nome:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(140, 430, 60, 17);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Data de Nascimento:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(440, 500, 120, 17);

        jTextFieldEndereco.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEndereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEndereco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(440, 450, 180, 25);
        jPanel1.add(jSeparator11);
        jSeparator11.setBounds(440, 480, 180, 10);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Endereço:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(450, 430, 60, 17);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Telefone:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(440, 350, 70, 17);
        jPanel1.add(jSeparator10);
        jSeparator10.setBounds(440, 410, 180, 10);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(140, 410, 180, 10);
        jPanel1.add(jSeparator9);
        jSeparator9.setBounds(140, 480, 180, 10);
        jPanel1.add(jSeparator13);
        jSeparator13.setBounds(440, 550, 180, 10);

        jFormattedTextFieldTelefoneA.setBorder(null);
        try {
            jFormattedTextFieldTelefoneA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefoneA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldTelefoneA.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(jFormattedTextFieldTelefoneA);
        jFormattedTextFieldTelefoneA.setBounds(440, 380, 180, 23);

        jButtonDelete1.setBackground(new java.awt.Color(102, 0, 0));
        jButtonDelete1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonDelete1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete1.setText("Responsáveis");
        jButtonDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete1ActionPerformed(evt);
            }
        });
        jButtonDelete1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonDelete1KeyPressed(evt);
            }
        });
        jPanel1.add(jButtonDelete1);
        jButtonDelete1.setBounds(720, 530, 110, 40);

        jTextFieldNome1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNome1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNome1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jTextFieldNome1);
        jTextFieldNome1.setBounds(140, 450, 180, 25);

        jTextFieldRg1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldRg1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRg1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jTextFieldRg1);
        jTextFieldRg1.setBounds(140, 520, 180, 25);

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("RG:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(140, 500, 70, 17);
        jPanel1.add(jSeparator14);
        jSeparator14.setBounds(140, 550, 180, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(861, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new HomeGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseClicked
        new HomeGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelHomeMouseClicked

    private void jPanelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseEntered
        setColor(jPanelHome);
    }//GEN-LAST:event_jPanelHomeMouseEntered

    private void jPanelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseExited
        resetColor(jPanelHome);
    }//GEN-LAST:event_jPanelHomeMouseExited

    private void jPanelAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseClicked
        new GereAlunosGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelAlunosMouseClicked

    private void jPanelAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseEntered
        setColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseEntered

    private void jPanelAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseExited
        resetColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseExited

    private void jPanelEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEstoqueMouseClicked
        new EstoqueGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelEstoqueMouseClicked

    private void jPanelEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEstoqueMouseEntered
        setColor(jPanelEstoque);
    }//GEN-LAST:event_jPanelEstoqueMouseEntered

    private void jPanelEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEstoqueMouseExited
        resetColor(jPanelEstoque);
    }//GEN-LAST:event_jPanelEstoqueMouseExited

    private void jPanelChamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelChamadaMouseClicked
        new ListaPresençaGUI().setVisible(true);;
        this.dispose();
    }//GEN-LAST:event_jPanelChamadaMouseClicked

    private void jPanelChamadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelChamadaMouseEntered
        setColor(jPanelChamada);
    }//GEN-LAST:event_jPanelChamadaMouseEntered

    private void jPanelChamadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelChamadaMouseExited
        resetColor(jPanelChamada);
    }//GEN-LAST:event_jPanelChamadaMouseExited

    private void jPanelCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastroMouseClicked
        new CadastroAlunoGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelCadastroMouseClicked

    private void jPanelCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastroMouseEntered
        setColor(jPanelCadastro);
    }//GEN-LAST:event_jPanelCadastroMouseEntered

    private void jPanelCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastroMouseExited
        resetColor(jPanelCadastro);
    }//GEN-LAST:event_jPanelCadastroMouseExited

    private void jButtonChamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChamaActionPerformed
        // Botão chama = Falta a estrutura de decisão para pegar a turma desejada.
        loadSampleData();
    }//GEN-LAST:event_jButtonChamaActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

        try {
            // Botão delete:
            dao.delete(lerPagina());
            DefaultTableModel model = (DefaultTableModel) jTableAlunos.getModel();
            model.setRowCount(0);
            loadSampleData();
            limpa();
        } catch (InvalidDataException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar apagar os dados:" + ex.getMessage());
        }


    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        try {
            // Botão Update:
            dao.update(lerPagina());
            DefaultTableModel model = (DefaultTableModel) jTableAlunos.getModel();
            model.setRowCount(0);
            loadSampleData();
            limpa();
        } catch (InvalidDataException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar ler os dados:" + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        // Método do tipo = "Enquanto for digitando" os dados que aparecem não tem um filtro por turma,
        // então pode aparecer dados das duas turmas
        pesquisarAluno();
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jTableAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunosMouseClicked
        //Mostra os dados da linha selecionada nos campos de texto
        int i = jTableAlunos.getSelectedRow();
        TableModel model = jTableAlunos.getModel();
        jTextFieldId.setText(model.getValueAt(i, 0).toString());
        jTextFieldNome1.setText(model.getValueAt(i, 1).toString());
        jTextFieldRg1.setText(model.getValueAt(i, 2).toString());
        jFormattedTextFieldTelefoneA.setText(model.getValueAt(i, 3).toString());
        jTextFieldEndereco.setText(model.getValueAt(i, 4).toString());
        jTextFieldDtNascimento.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTableAlunosMouseClicked

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jButtonChamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonChamaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            getRootPane().setDefaultButton(jButtonChama);
        }
    }//GEN-LAST:event_jButtonChamaKeyPressed

    private void jButtonAtualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAtualizarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            getRootPane().setDefaultButton(jButtonAtualizar);
        }
    }//GEN-LAST:event_jButtonAtualizarKeyPressed

    private void jButtonDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDeleteKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            getRootPane().setDefaultButton(jButtonDelete);
        }
    }//GEN-LAST:event_jButtonDeleteKeyPressed

    private void jButtonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete1ActionPerformed
        new GereResponsavel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonDelete1ActionPerformed

    private void jButtonDelete1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDelete1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelete1KeyPressed

    void loadSampleData() {

        JTableHeader header = jTableAlunos.getTableHeader();
        DefaultTableCellRenderer center = (DefaultTableCellRenderer) header.getDefaultRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        /* Centralizar e alinhar a esquerda o id e o nome na tabela*/
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        left.setHorizontalAlignment(SwingConstants.LEFT);
        jTableAlunos.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTableAlunos.getColumnModel().getColumn(1).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(2).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(3).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(4).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(5).setCellRenderer(left);
        // Método para pegar os dados do banco de dados
        try {
            Connection con = null;
            PreparedStatement ps = null;
            String sql = "SELECT id_aluno, nome, rg, telefone, endereco, dt_nascimento FROM ALUNO order by nome";

            con = UtilDAO.conectar();
            ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (jTableAlunos.getRowCount() > 0) {
                ((DefaultTableModel) jTableAlunos.getModel()).removeRow(0);
            }
            int col = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {

                    rows[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) jTableAlunos.getModel()).insertRow(rs.getRow() - 1, rows);
            }

            rs.close();
            ps.close();
        } catch (SQLException e) {

        }

    }

    private void pesquisarAluno() {

        JTableHeader header = jTableAlunos.getTableHeader();
        DefaultTableCellRenderer center = (DefaultTableCellRenderer) header.getDefaultRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        /* Centralizar e alinhar a esquerda o id e o nome na tabela*/
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        left.setHorizontalAlignment(SwingConstants.LEFT);
        jTableAlunos.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTableAlunos.getColumnModel().getColumn(1).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(2).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(3).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(4).setCellRenderer(left);
        jTableAlunos.getColumnModel().getColumn(5).setCellRenderer(left);
        try {
            Connection con = null;
            PreparedStatement ps = null;
            String sql = "SELECT * FROM ALUNO WHERE NOME LIKE ?";
            con = UtilDAO.conectar();
            ps = con.prepareStatement(sql);
            ps.setString(1, "%" + jTextFieldSearch.getText() + "%");
            ResultSet rs = ps.executeQuery();

            /* A linha abaixo é referente a biblioteca rs2xml, ela preenche a
            tabela conforme o que for digitado no campo */
            jTableAlunos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {

        }
    }

    private CadastroAluno lerPagina() throws InvalidDataException {
        int id = Integer.parseInt(jTextFieldId.getText());
        a.setId_aluno(id);
        a.setNome(UtilGUI.validaDados(jTextFieldNome1.getText()));
        a.setRg(UtilGUI.validaDados(jTextFieldRg1.getText()));
        a.setTelefone(UtilGUI.validaDados(jFormattedTextFieldTelefoneA.getText()));
        a.setEndereco(UtilGUI.validaDados(jTextFieldEndereco.getText()));
        a.setDtNasc(UtilGUI.validaDados(jTextFieldDtNascimento.getText()));
        return a;
    }

    private void limpa() {
        jTextFieldDtNascimento.setText(null);
        jTextFieldId.setText(null);
        jFormattedTextFieldTelefoneA.setText(null);
        jTextFieldEndereco.setText(null);
        jFormattedTextFieldTelefoneA.setText(null);
        jTextFieldNome1.setText(null);
        jTextFieldRg1.setText(null);
    }

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 0, 0));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(102, 0, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GereAlunosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GereAlunosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GereAlunosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GereAlunosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GereAlunosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonChama;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDelete1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlunos;
    private javax.swing.JLabel jLabelEstoque;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAlunos;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelChamada;
    private javax.swing.JPanel jPanelEstoque;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableAlunos;
    private javax.swing.JTextField jTextFieldDtNascimento;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome1;
    private javax.swing.JTextField jTextFieldRg1;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
    public CadastroAluno a = new CadastroAluno();
    public CadastroAlunoDAO dao = new CadastroAlunoDAO();
}
