/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.etec.GUI;

import br.gov.sp.etec.DAO.MensalidadeDAO;
import br.gov.sp.etec.modelagem.Mensalidades;
import br.gov.sp.etec.conectar.UtilDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Tami
 */
public class MensalidadesGUI extends javax.swing.JFrame {

    /**
     * Creates new form Modelo
     */
    public MensalidadesGUI() {
        initComponents();
        jButtonApagar.setVisible(false);
    }

    String mes = "";
    boolean prossiga;
    int contador;
    String conta[] = new String[50];
    String nome[] = new String[50];
    boolean pendente[] = new boolean[50];
    String vencimento[] = new String[50];
    MensalidadeDAO dao = new MensalidadeDAO();
    Mensalidades m = new Mensalidades();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMinimizar1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jPanelAlunos = new javax.swing.JPanel();
        jLabelAlunos = new javax.swing.JLabel();
        jPanelEstoque = new javax.swing.JPanel();
        jLabelEstoque = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelChamada = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonChamar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setToolTipText("Fechar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/icons8_Money_Transfer_32px.png"))); // NOI18N
        jLabel5.setText("Mensalidade");

        jLabelMinimizar1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMinimizar1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelMinimizar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar1.setText("_");
        jLabelMinimizar1.setToolTipText("Minimizar");
        jLabelMinimizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel5)
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMinimizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(121, 1, 740, 100);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(130, 525));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Voltar_18px.png"))); // NOI18N
        jLabel2.setText("Voltar");
        jLabel2.setToolTipText("Voltar para tela Home");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setDoubleBuffered(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanelHome.setBackground(new java.awt.Color(102, 0, 0));
        jPanelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelHome.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseExited(evt);
            }
        });

        jLabelHome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Home_18px.png"))); // NOI18N
        jLabelHome.setText("Home");
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAlunos.setBackground(new java.awt.Color(102, 0, 0));
        jPanelAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAlunos.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseExited(evt);
            }
        });

        jLabelAlunos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlunos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Alunos_18px.png"))); // NOI18N
        jLabelAlunos.setText("Alunos");

        javax.swing.GroupLayout jPanelAlunosLayout = new javax.swing.GroupLayout(jPanelAlunos);
        jPanelAlunos.setLayout(jPanelAlunosLayout);
        jPanelAlunosLayout.setHorizontalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlunos)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelAlunosLayout.setVerticalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelEstoque.setBackground(new java.awt.Color(102, 0, 0));
        jPanelEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelEstoque.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEstoqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEstoqueMouseExited(evt);
            }
        });

        jLabelEstoque.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Estoque_18px.png"))); // NOI18N
        jLabelEstoque.setText("Estoque");
        jLabelEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelEstoqueLayout = new javax.swing.GroupLayout(jPanelEstoque);
        jPanelEstoque.setLayout(jPanelEstoqueLayout);
        jPanelEstoqueLayout.setHorizontalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEstoque)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelEstoqueLayout.setVerticalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Cabeçalho.png"))); // NOI18N

        jPanelChamada.setBackground(new java.awt.Color(102, 0, 0));
        jPanelChamada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelChamada.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelChamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelChamadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelChamadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelChamadaMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Chamada_18px_1.png"))); // NOI18N
        jLabel7.setText("Chamada");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelChamadaLayout = new javax.swing.GroupLayout(jPanelChamada);
        jPanelChamada.setLayout(jPanelChamadaLayout);
        jPanelChamadaLayout.setHorizontalGroup(
            jPanelChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChamadaLayout.setVerticalGroup(
            jPanelChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastro.setBackground(new java.awt.Color(102, 0, 0));
        jPanelCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCadastro.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanelCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCadastroMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gov/sp/etec/icons/Cadastro_18px_3.png"))); // NOI18N
        jLabel9.setText("Cadastro");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanelAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanelChamada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1, 1, 120, 590);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Pendente", "Mês"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 720, 250);

        jButtonSalvar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonSalvar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(760, 510, 90, 40);

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kids", "Juvenil - Adulto" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(130, 110, 120, 20);

        jButtonChamar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonChamar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonChamar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChamar.setText("Selecionar");
        jButtonChamar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChamarActionPerformed(evt);
            }
        });
        jButtonChamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonChamarKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonChamar);
        jButtonChamar.setBounds(130, 140, 110, 40);

        jButtonEditar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonEditar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Mensalidades em atraso");
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jButtonEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonEditarKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(640, 140, 210, 40);

        jComboBoxMes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jPanel1.add(jComboBoxMes);
        jComboBoxMes.setBounds(380, 110, 100, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Mês:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 110, 30, 20);

        jButtonApagar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonApagar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonApagar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonApagar.setText("Apagar registro");
        jButtonApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        jButtonApagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonApagarKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonApagar);
        jButtonApagar.setBounds(560, 510, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(861, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new HomeGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseClicked
        new HomeGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelHomeMouseClicked

    private void jPanelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseEntered
        setColor(jPanelHome);
    }//GEN-LAST:event_jPanelHomeMouseEntered

    private void jPanelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseExited
        resetColor(jPanelHome);
    }//GEN-LAST:event_jPanelHomeMouseExited

    private void jPanelAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseClicked
        new GereAlunosGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelAlunosMouseClicked

    private void jPanelAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseEntered
        setColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseEntered

    private void jPanelAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseExited
        resetColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseExited

    private void jPanelEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEstoqueMouseClicked
        new EstoqueGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelEstoqueMouseClicked

    private void jPanelEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEstoqueMouseEntered
        setColor(jPanelEstoque);
    }//GEN-LAST:event_jPanelEstoqueMouseEntered

    private void jPanelEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEstoqueMouseExited
        resetColor(jPanelEstoque);
    }//GEN-LAST:event_jPanelEstoqueMouseExited

    private void jPanelChamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelChamadaMouseClicked
        new ListaPresençaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelChamadaMouseClicked

    private void jPanelChamadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelChamadaMouseEntered
        setColor(jPanelChamada);
    }//GEN-LAST:event_jPanelChamadaMouseEntered

    private void jPanelChamadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelChamadaMouseExited
        resetColor(jPanelChamada);
    }//GEN-LAST:event_jPanelChamadaMouseExited

    private void jPanelCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastroMouseClicked
        new CadastroAlunoGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelCadastroMouseClicked

    private void jPanelCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastroMouseEntered
        setColor(jPanelCadastro);
    }//GEN-LAST:event_jPanelCadastroMouseEntered

    private void jPanelCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCadastroMouseExited
        resetColor(jPanelCadastro);
    }//GEN-LAST:event_jPanelCadastroMouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        lerCheckBox();
    }//GEN-LAST:event_jTable1MouseClicked

    public boolean verificarMes() {
        mes = jComboBoxMes.getSelectedItem().toString();

        if (mes.equalsIgnoreCase("selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um mês!", "ERRO", 0);
            prossiga = false;
        } else {
            prossiga = true;
        }

        return prossiga;
    }

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // Botão Salvar = Pergunta ao usuário se ele deseja salvar as alterações(chamada),
        // pega os dados salvo em vetores, e envia ao banco de dados
        int result = 0;

        if (verificarMes() == true) {
            result = JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "AVISO", JOptionPane.YES_NO_CANCEL_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    if (nome[i] != null && pendente[i] != false) {
                        m.setId_aluno(Integer.parseInt(conta[i]));
                        m.setMes(jComboBoxMes.getSelectedItem().toString());
                        m.setPendente(pendente[i]);
                        m.setNome(nome[i]);
                        dao.insert(m);
                    }
                }
                JOptionPane.showMessageDialog(null, "Dados inseridos!", "Sucesso", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Operação cancelada!", "ERRO", 0);
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChamarActionPerformed
        // Botão Chamar = Há uma estrutura de decisão para pegar os dados da turma desejada junto com  o banco de dados

        jButtonSalvar.setEnabled(true);
        jButtonApagar.setVisible(false);
        jButtonApagar.setEnabled(false);

        if (jComboBox1.getSelectedItem().equals("Kids")) {
            loadSampleData();
        } else if (jComboBox1.getSelectedItem().equals("Juvenil - Adulto")) {
            loadSampleDataB();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao buscar a lista de alunos");
        }
    }//GEN-LAST:event_jButtonChamarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        loadSalvo();
        jButtonSalvar.setEnabled(false);
        jButtonApagar.setVisible(true);
        jButtonApagar.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jLabelMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizar1MouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizar1MouseClicked

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        int i;
        int result;
        i = jTable1.getSelectedRow();
        m.setId_mensalidade((Integer.parseInt(jTable1.getValueAt(i, 0).toString())));
        result = JOptionPane.showConfirmDialog(null, "Deseja apagar esse registro?", "AVISO", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            dao.delete(m);
            loadSalvo();
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!", "ERRO", 0);
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonChamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonChamarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            getRootPane().setDefaultButton(jButtonChamar);
        }
    }//GEN-LAST:event_jButtonChamarKeyPressed

    private void jButtonEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonEditarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            getRootPane().setDefaultButton(jButtonEditar);
        }
    }//GEN-LAST:event_jButtonEditarKeyPressed

    private void jButtonApagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonApagarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            getRootPane().setDefaultButton(jButtonApagar);
        }
    }//GEN-LAST:event_jButtonApagarKeyPressed

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            getRootPane().setDefaultButton(jButtonSalvar);
        }
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    void loadSampleData() {
        /* Centralizar o título da tabela */
        JTableHeader header = jTable1.getTableHeader();
        DefaultTableCellRenderer center = (DefaultTableCellRenderer) header.getDefaultRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        /* Centralizar e alinhar a esquerda o id e o nome na tabela*/
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        left.setHorizontalAlignment(SwingConstants.LEFT);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(left);

        /* Método para buscar os dados no banco de dados e preencher na tabela */
        try {
            Connection con = null;
            PreparedStatement ps = null;
            String sql = "SELECT id_aluno, nome FROM aluno order by nome";

            con = UtilDAO.conectar();
            ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (jTable1.getRowCount() > 0) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }
            int col = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {

                    rows[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
            }

            rs.close();
            ps.close();
        } catch (SQLException e) {

        }

    }

    void loadSampleDataB() {
        /* Método para buscar os dados no banco de dados e preencher na tabela */
        try {
            Connection con = null;
            PreparedStatement ps = null;
            String sql = "SELECT * FROM chamadab order by nome";

            con = UtilDAO.conectar();
            ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (jTable1.getRowCount() > 0) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }
            int col = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {

                    rows[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
            }

            rs.close();
            ps.close();
        } catch (SQLException e) {

        }

    }

    void loadSalvo() {
        /* Centralizar o título da tabela */
        JTableHeader header = jTable1.getTableHeader();
        DefaultTableCellRenderer center = (DefaultTableCellRenderer) header.getDefaultRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        /* Centralizar e alinhar a esquerda o id e o nome na tabela*/
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        left.setHorizontalAlignment(SwingConstants.LEFT);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(left);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(left);
        
        /* Método para buscar os dados no banco de dados e preencher na tabela */
        try {
            Connection con = null;
            PreparedStatement ps = null;
            String sql = "SELECT id_mensalidade, nome_aluno, pendente, mes FROM mensalidade order by nome_aluno";

            con = UtilDAO.conectar();
            ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (jTable1.getRowCount() > 0) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }
            int col = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {

                    rows[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
            }

            rs.close();
            ps.close();
        } catch (SQLException e) {

        }

    }

    void lerCheckBox() { // Método para pegar os dados quando um checkbox estiver marcado;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Boolean check = (Boolean) jTable1.getValueAt(i, 2); //coluna onde esta os checkbox
            if (check != null) {
                conta[i] = (String) jTable1.getValueAt(i, 0).toString();
                nome[i] = (String) jTable1.getValueAt(i, 1);
                pendente[i] = (Boolean) jTable1.getValueAt(i, 2);
            }
        }
    }

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 0, 0));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(102, 0, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensalidadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensalidadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensalidadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensalidadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MensalidadesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonChamar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlunos;
    private javax.swing.JLabel jLabelEstoque;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelMinimizar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAlunos;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelChamada;
    private javax.swing.JPanel jPanelEstoque;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
